const enemy = 'enemy';
const enemy_fast = 'enemy_fast';
const enemy_large = 'enemy_large';
const enemy_blue = 'enemy_blue';
const enemy_flying = 'enemy_flying';

const ENEMY_WAVES = [
  // time: seconds from game start
  // enemy: enemy | enemy_fast | enemy_large | enemy_blue | enemy_flying
  // count: number of enemies in the wave
  // enemy_flying spawns from both sides; use even counts for perfect symmetry
  { time: 2, enemy: enemy, count: 8 },
  { time: 6, enemy: enemy, count: 8 },
  { time: 9, enemy: enemy, count: 10 },
  { time: 10, enemy: enemy_blue, count: 2 },
  { time: 12, enemy: enemy, count: 5 },
  { time: 15, enemy: enemy_blue, count: 3 },
  { time: 18, enemy: enemy, count: 6 },
  { time: 20, enemy: enemy_fast, count: 2 },
  { time: 22, enemy: enemy, count: 6 },
  { time: 24, enemy: enemy_blue, count: 3 },
  { time: 27, enemy: enemy, count: 7 },
  { time: 30, enemy: enemy_flying, count: 2 },
  { time: 32, enemy: enemy_fast, count: 3 },
  { time: 35, enemy: enemy, count: 7 },
  { time: 38, enemy: enemy_blue, count: 4 },
  { time: 40, enemy: enemy_large, count: 2 },
  { time: 42, enemy: enemy, count: 8 },
  { time: 45, enemy: enemy_flying, count: 2 },
  { time: 48, enemy: enemy_fast, count: 3 },
  { time: 50, enemy: enemy_blue, count: 4 },
  { time: 53, enemy: enemy, count: 8 },
  { time: 56, enemy: enemy_flying, count: 4 },
  { time: 58, enemy: enemy_fast, count: 4 },
  { time: 60, enemy: enemy_large, count: 2 },
  { time: 63, enemy: enemy, count: 9 },
  { time: 66, enemy: enemy_blue, count: 5 },
  { time: 69, enemy: enemy_fast, count: 4 },
  { time: 72, enemy: enemy_flying, count: 4 },
  { time: 75, enemy: enemy, count: 9 },
  { time: 78, enemy: enemy_large, count: 2 },
  { time: 81, enemy: enemy_blue, count: 5 },
  { time: 84, enemy: enemy_fast, count: 4 },
  { time: 87, enemy: enemy_flying, count: 4 },
  { time: 90, enemy: enemy, count: 10 },
  { time: 93, enemy: enemy_blue, count: 6 },
  { time: 96, enemy: enemy_fast, count: 5 },
  { time: 99, enemy: enemy_flying, count: 4 },
  { time: 102, enemy: enemy_large, count: 3 },
  { time: 105, enemy: enemy, count: 10 },
  { time: 108, enemy: enemy_blue, count: 6 },
  { time: 111, enemy: enemy_fast, count: 5 },
  { time: 114, enemy: enemy_flying, count: 4 },
  { time: 117, enemy: enemy, count: 11 },
  { time: 120, enemy: enemy_large, count: 3 },
  { time: 123, enemy: enemy_blue, count: 6 },
  { time: 126, enemy: enemy_fast, count: 6 },
  { time: 129, enemy: enemy_flying, count: 4 },
  { time: 132, enemy: enemy, count: 11 },
  { time: 135, enemy: enemy_blue, count: 7 },
  { time: 138, enemy: enemy_fast, count: 6 },
  { time: 141, enemy: enemy_flying, count: 4 },
  { time: 144, enemy: enemy_large, count: 3 },
  { time: 147, enemy: enemy, count: 12 },
  { time: 150, enemy: enemy_blue, count: 7 },
  { time: 153, enemy: enemy_fast, count: 6 },
  { time: 156, enemy: enemy_flying, count: 4 },
  { time: 159, enemy: enemy, count: 12 },
  { time: 162, enemy: enemy_large, count: 3 },
  { time: 165, enemy: enemy_blue, count: 7 },
  { time: 168, enemy: enemy_fast, count: 7 },
  { time: 171, enemy: enemy_flying, count: 6 },
  { time: 174, enemy: enemy, count: 13 },
  { time: 177, enemy: enemy_blue, count: 8 },
  { time: 180, enemy: enemy_fast, count: 7 },
  { time: 183, enemy: enemy_flying, count: 6 },
  { time: 186, enemy: enemy_large, count: 4 },
  { time: 189, enemy: enemy, count: 13 },
  { time: 192, enemy: enemy_blue, count: 8 },
  { time: 195, enemy: enemy_fast, count: 7 },
  { time: 198, enemy: enemy_flying, count: 6 },
  { time: 201, enemy: enemy, count: 14 },
  { time: 204, enemy: enemy_large, count: 4 },
  { time: 207, enemy: enemy_blue, count: 8 },
  { time: 210, enemy: enemy_fast, count: 8 },
  { time: 213, enemy: enemy_flying, count: 6 },
  { time: 216, enemy: enemy, count: 14 },
  { time: 219, enemy: enemy_blue, count: 9 },
  { time: 222, enemy: enemy_fast, count: 8 },
  { time: 225, enemy: enemy_flying, count: 6 },
  { time: 228, enemy: enemy_large, count: 4 },
  { time: 231, enemy: enemy, count: 15 },
  { time: 234, enemy: enemy_blue, count: 9 },
  { time: 237, enemy: enemy_fast, count: 8 },
  { time: 240, enemy: enemy_flying, count: 6 },
  { time: 243, enemy: enemy, count: 15 },
  { time: 246, enemy: enemy_large, count: 5 },
  { time: 249, enemy: enemy_blue, count: 9 },
  { time: 252, enemy: enemy_fast, count: 9 },
  { time: 255, enemy: enemy_flying, count: 6 },
  { time: 258, enemy: enemy, count: 16 },
  { time: 261, enemy: enemy_blue, count: 10 },
  { time: 264, enemy: enemy_fast, count: 9 },
  { time: 267, enemy: enemy_flying, count: 8 },
  { time: 270, enemy: enemy_large, count: 5 },
  { time: 273, enemy: enemy, count: 16 },
  { time: 276, enemy: enemy_blue, count: 10 },
  { time: 279, enemy: enemy_fast, count: 9 },
  { time: 282, enemy: enemy_flying, count: 8 },
  { time: 285, enemy: enemy, count: 17 },
  { time: 288, enemy: enemy_large, count: 5 },
  { time: 291, enemy: enemy_blue, count: 10 },
  { time: 294, enemy: enemy_fast, count: 10 },
  { time: 297, enemy: enemy_flying, count: 8 },
  { time: 300, enemy: enemy, count: 18 },
];

export { ENEMY_WAVES };
